import { h } from 'vue'
import type { IconSet, IconAliases, IconProps } from 'vuetify'
import {
    IconCalendarFilled,
    IconCircleXFilled,
    IconX,
    IconPaperclip,
    IconChevronRight,
    IconChevronLeft,
    IconCaretDownFilled,
    IconSquareCheckFilled,
    IconSquare,
    IconSquareMinusFilled,
    IconChevronUp,
    IconCheck,
    IconCircleFilled,
    IconPencil,
    IconChevronDown,
    IconColorPicker,
    IconChevronLeftPipe,
    IconInfoCircleFilled,
    IconChevronRightPipe,
    IconRefresh,
    IconMenu2,
    IconMinus,
    IconPlus,
    IconCircle,
    IconCircleCheckFilled,
    IconStar,
    IconStarFilled,
    IconStarHalfFilled,
    IconArrowUp,
    IconArrowDown,
    IconSelector,
    IconAlertCircleFilled,
} from '@tabler/icons-vue'

const aliases: IconAliases = {
    calendar: IconCalendarFilled,
    cancel: IconCircleXFilled,
    checkboxIndeterminate: IconSquareMinusFilled,
    checkboxOff: IconSquare,
    checkboxOn: IconSquareCheckFilled,
    clear: IconCircleXFilled,
    close: IconX,
    collapse: IconChevronUp,
    complete: IconCheck,
    delete: IconCircleXFilled,
    delimiter: IconCircleFilled,
    dropdown: IconCaretDownFilled,
    edit: IconPencil,
    error: IconCircleXFilled,
    expand: IconChevronDown,
    eyeDropper: IconColorPicker,
    file: IconPaperclip,
    first: IconChevronLeftPipe,
    info: IconInfoCircleFilled,
    last: IconChevronRightPipe,
    loading: IconRefresh,
    menu: IconMenu2,
    minus: IconMinus,
    next: IconChevronRight,
    plus: IconPlus,
    prev: IconChevronLeft,
    radioOff: IconCircle,
    radioOn: IconCircleCheckFilled,
    ratingEmpty: IconStar,
    ratingFull: IconStarFilled,
    ratingHalf: IconStarHalfFilled,
    sortAsc: IconArrowUp,
    sortDesc: IconArrowDown,
    subgroup: IconCaretDownFilled,
    success: IconCircleCheckFilled,
    unfold: IconSelector,
    warning: IconAlertCircleFilled,
}

const custom: IconSet = {
    component: (props: IconProps) => h(props.tag, { class: [props.icon] }),
}

export { aliases, custom }
